# Generated by Django 3.2.16 on 2023-01-29 18:28

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration_units', '0004_auto_20230129_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrationunit',
            name='gps_location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
