# Generated by Django 3.2.16 on 2023-01-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0008_user_subscribed_to_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_fully_specified',
            field=models.BooleanField(default=False),
        ),
    ]
