# Generated by Django 3.2.16 on 2023-01-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0010_eycacard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='online_link',
            field=models.URLField(blank=True, help_text='Vyplňte, pokud se akce koná online'),
        ),
    ]
