# Generated by Django 3.2.17 on 2023-02-11 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration_units', '0005_administrationunit_gps_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_book_categories', '0004_auto_20230208_0027'),
        ('game_book', '0002_auto_20230208_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='administration_unit',
            field=models.ForeignKey(blank=True, help_text='Chceš program přiřadit pod určitý článek? Dej mu kredit!', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='administration_units.administrationunit'),
        ),
        migrations.AlterField(
            model_name='game',
            name='contributor',
            field=models.ForeignKey(help_text='Kdo zadal program do sborníku?', on_delete=django.db.models.deletion.PROTECT, related_name='games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(help_text='Popis a pravidla programu'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_length_note',
            field=models.TextField(blank=True, help_text='Specifické poznámky k délce programu'),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Editor může program skrýt (autorské práva, nekorektní text, atd.)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_original',
            field=models.BooleanField(default=False, help_text='Jsi autorem tohoto programu — vytvořil si ho? Pokud ne, vyplň původ programu níže.'),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Editor může program ověřit, záruka brontosauří kvality'),
        ),
        migrations.AlterField(
            model_name='game',
            name='location_category',
            field=models.ManyToManyField(help_text='Typová místa, na kterých lze / dává smysl program uvést', related_name='games', to='game_book_categories.LocationCategory'),
        ),
        migrations.AlterField(
            model_name='game',
            name='location_note',
            field=models.TextField(blank=True, help_text='Specifické poznámky k místu uvedení'),
        ),
        migrations.AlterField(
            model_name='game',
            name='material_requirement_note',
            field=models.TextField(blank=True, help_text='Specifické poznámky k množství materiálu'),
        ),
        migrations.AlterField(
            model_name='game',
            name='mental_note',
            field=models.TextField(blank=True, help_text='Specifické poznámky k psychické náročnosti'),
        ),
        migrations.AlterField(
            model_name='game',
            name='motivation',
            field=models.TextField(blank=True, help_text='Tipy na vtáhnutí účastníků do hry (scénkou, hudbou, aktivitkou)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='notes',
            field=models.TextField(blank=True, help_text='Tipy a triky pro uvedení, otázky na reflexi, atd.'),
        ),
        migrations.AlterField(
            model_name='game',
            name='organizers_number_note',
            field=models.TextField(blank=True, help_text='Specifické poznámky k počtu orgů pro uvedení programu'),
        ),
        migrations.AlterField(
            model_name='game',
            name='origin',
            field=models.TextField(blank=True, help_text='Kdo je autorem programu, odkud byl program převzat?'),
        ),
        migrations.AlterField(
            model_name='game',
            name='participant_age_note',
            field=models.TextField(blank=True, help_text='Specifické poznámky k věku účastníků'),
        ),
        migrations.AlterField(
            model_name='game',
            name='participant_number_note',
            field=models.TextField(blank=True, help_text='Specifické poznámky k počtu účastníků'),
        ),
        migrations.AlterField(
            model_name='game',
            name='physical_note',
            field=models.TextField(blank=True, help_text='Specifické poznámky k fyzické náročnosti'),
        ),
        migrations.AlterField(
            model_name='game',
            name='preparation_length_note',
            field=models.TextField(blank=True, help_text='Specifické poznámky k délce / náročnosti přípravy programu'),
        ),
        migrations.AlterField(
            model_name='game',
            name='short_description',
            field=models.CharField(help_text='Maximálně 250 znaků', max_length=250),
        ),
        migrations.AlterField(
            model_name='game',
            name='stars',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], help_text='Interní hodnocení pro editory', null=True),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='game_lists', to='game_book.Game'),
        ),
    ]
