# Generated by Django 3.2.17 on 2023-02-20 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_book', '0005_alter_game_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='gamelist',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='playedat',
            options={'ordering': ('-id',)},
        ),
    ]
