# Generated by Django 3.2.17 on 2023-02-24 21:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('game_book', '0006_auto_20230220_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='material',
            field=tinymce.models.HTMLField(default='', help_text='Co je potřeba k uvedení hry, soubory pro tisk lze přiložit níže'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=tinymce.models.HTMLField(help_text='Popis a pravidla programu'),
        ),
        migrations.AlterField(
            model_name='game',
            name='goal',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='motivation',
            field=tinymce.models.HTMLField(blank=True, help_text='Tipy na vtáhnutí účastníků do hry (scénkou, hudbou, aktivitkou)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='notes',
            field=tinymce.models.HTMLField(blank=True, help_text='Tipy a triky pro uvedení, otázky na reflexi, atd.'),
        ),
    ]
