# Generated by Django 3.2.17 on 2023-02-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_book_categories', '0002_auto_20230208_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelengthcategory',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='locationcategory',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='materialrequirementcategory',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='mentalcategory',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='organizersnumbercategory',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='participantagecategory',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='participantnumbercategory',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='physicalcategory',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='preparationlengthcategory',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
