# Generated by Django 3.2.17 on 2023-02-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_book_categories', '0003_auto_20230208_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelengthcategory',
            name='description',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='locationcategory',
            name='description',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='materialrequirementcategory',
            name='description',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='mentalcategory',
            name='description',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='organizersnumbercategory',
            name='description',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='participantagecategory',
            name='description',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='participantnumbercategory',
            name='description',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='physicalcategory',
            name='description',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='preparationlengthcategory',
            name='description',
            field=models.CharField(max_length=120),
        ),
    ]
