# Generated by Django 3.2.16 on 2023-02-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20221231_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualificationcategory',
            name='can_approve',
            field=models.ManyToManyField(related_name='can_be_approved_with', to='categories.QualificationCategory'),
        ),
    ]
