# Generated by Django 3.2.16 on 2023-01-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_eventapplication_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='question',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
